import enum
import json
from typing import Any, Dict, List, Optional, Tuple, Type

def build_msp_codes_enum(defs: Dict[str, Any]) -> Type[enum.IntEnum]:
    members: Dict[str, int] = {}
    for name, body in defs.items():
        try:
            code = int(body.get("code", -1))
        except (TypeError, ValueError):
            continue
        members[name] = code
    return enum.IntEnum("MSPCodes", members)

class BF_MSPCodes(enum.IntEnum):
    MSP_API_VERSION = 1
    MSP_FC_VARIANT = 2
    MSP_FC_VERSION = 3
    MSP_BOARD_INFO = 4
    MSP_BUILD_INFO = 5
    MSP_NAME = 10
    MSP_SET_NAME = 11
    MSP_BATTERY_CONFIG = 32
    MSP_SET_BATTERY_CONFIG = 33
    MSP_MODE_RANGES = 34
    MSP_SET_MODE_RANGE = 35
    MSP_FEATURE_CONFIG = 36
    MSP_SET_FEATURE_CONFIG = 37
    MSP_BOARD_ALIGNMENT_CONFIG = 38
    MSP_SET_BOARD_ALIGNMENT_CONFIG = 39
    MSP_CURRENT_METER_CONFIG = 40
    MSP_SET_CURRENT_METER_CONFIG = 41
    MSP_MIXER_CONFIG = 42
    MSP_SET_MIXER_CONFIG = 43
    MSP_RX_CONFIG = 44
    MSP_SET_RX_CONFIG = 45
    MSP_LED_COLORS = 46
    MSP_SET_LED_COLORS = 47
    MSP_LED_STRIP_CONFIG = 48
    MSP_SET_LED_STRIP_CONFIG = 49
    MSP_RSSI_CONFIG = 50
    MSP_SET_RSSI_CONFIG = 51
    MSP_ADJUSTMENT_RANGES = 52
    MSP_SET_ADJUSTMENT_RANGE = 53
    MSP_CF_SERIAL_CONFIG = 54
    MSP_SET_CF_SERIAL_CONFIG = 55
    MSP_VOLTAGE_METER_CONFIG = 56
    MSP_SET_VOLTAGE_METER_CONFIG = 57
    MSP_SONAR_ALTITUDE = 58
    MSP_PID_CONTROLLER = 59
    MSP_SET_PID_CONTROLLER = 60
    MSP_ARMING_CONFIG = 61
    MSP_SET_ARMING_CONFIG = 62
    MSP_RX_MAP = 64
    MSP_SET_RX_MAP = 65
    MSP_REBOOT = 68
    MSP_DATAFLASH_SUMMARY = 70
    MSP_DATAFLASH_READ = 71
    MSP_DATAFLASH_ERASE = 72
    MSP_FAILSAFE_CONFIG = 75
    MSP_SET_FAILSAFE_CONFIG = 76
    MSP_RXFAIL_CONFIG = 77
    MSP_SET_RXFAIL_CONFIG = 78
    MSP_SDCARD_SUMMARY = 79
    MSP_BLACKBOX_CONFIG = 80
    MSP_SET_BLACKBOX_CONFIG = 81
    MSP_TRANSPONDER_CONFIG = 82
    MSP_SET_TRANSPONDER_CONFIG = 83
    MSP_OSD_CONFIG = 84
    MSP_SET_OSD_CONFIG = 85
    MSP_OSD_CHAR_READ = 86
    MSP_OSD_CHAR_WRITE = 87
    MSP_VTX_CONFIG = 88
    MSP_SET_VTX_CONFIG = 89
    MSP_ADVANCED_CONFIG = 90
    MSP_SET_ADVANCED_CONFIG = 91
    MSP_FILTER_CONFIG = 92
    MSP_SET_FILTER_CONFIG = 93
    MSP_PID_ADVANCED = 94
    MSP_SET_PID_ADVANCED = 95
    MSP_SENSOR_CONFIG = 96
    MSP_SET_SENSOR_CONFIG = 97
    MSP_CAMERA_CONTROL = 98
    MSP_SET_ARMING_DISABLED = 99
    MSP_IDENT = 100
    MSP_STATUS = 101
    MSP_RAW_IMU = 102
    MSP_SERVO = 103
    MSP_MOTOR = 104
    MSP_RC = 105
    MSP_RAW_GPS = 106
    MSP_COMP_GPS = 107
    MSP_ATTITUDE = 108
    MSP_ALTITUDE = 109
    MSP_ANALOG = 110
    MSP_RC_TUNING = 111
    MSP_PID = 112
    MSP_BOXNAMES = 116
    MSP_PIDNAMES = 117
    MSP_WP = 118
    MSP_BOXIDS = 119
    MSP_SERVO_CONFIGURATIONS = 120
    MSP_NAV_STATUS = 121
    MSP_NAV_CONFIG = 122
    MSP_MOTOR_3D_CONFIG = 124
    MSP_RC_DEADBAND = 125
    MSP_SENSOR_ALIGNMENT = 126
    MSP_LED_STRIP_MODECOLOR = 127
    MSP_VOLTAGE_METERS = 128
    MSP_CURRENT_METERS = 129
    MSP_BATTERY_STATE = 130
    MSP_MOTOR_CONFIG = 131
    MSP_GPS_CONFIG = 132
    MSP_COMPASS_CONFIG = 133
    MSP_ESC_SENSOR_DATA = 134
    MSP_GPS_RESCUE = 135
    MSP_GPS_RESCUE_PIDS = 136
    MSP_VTXTABLE_BAND = 137
    MSP_VTXTABLE_POWERLEVEL = 138
    MSP_MOTOR_TELEMETRY = 139
    MSP_SIMPLIFIED_TUNING = 140
    MSP_SET_SIMPLIFIED_TUNING = 141
    MSP_CALCULATE_SIMPLIFIED_PID = 142
    MSP_CALCULATE_SIMPLIFIED_GYRO = 143
    MSP_CALCULATE_SIMPLIFIED_DTERM = 144
    MSP_VALIDATE_SIMPLIFIED_TUNING = 145
    MSP_STATUS_EX = 150
    MSP_UID = 160
    MSP_GPSSVINFO = 164
    MSP_GPSSTATISTICS = 166
    MSP_OSD_VIDEO_CONFIG = 180
    MSP_SET_OSD_VIDEO_CONFIG = 181
    MSP_DISPLAYPORT = 182
    MSP_COPY_PROFILE = 183
    MSP_BEEPER_CONFIG = 184
    MSP_SET_BEEPER_CONFIG = 185
    MSP_SET_TX_INFO = 186
    MSP_TX_INFO = 187
    MSP_SET_OSD_CANVAS = 188
    MSP_OSD_CANVAS = 189
    MSP_SET_RAW_RC = 200
    MSP_SET_RAW_GPS = 201
    MSP_SET_PID = 202
    MSP_SET_RC_TUNING = 204
    MSP_ACC_CALIBRATION = 205
    MSP_MAG_CALIBRATION = 206
    MSP_RESET_CONF = 208
    MSP_SET_WP = 209
    MSP_SELECT_SETTING = 210
    MSP_SET_HEADING = 211
    MSP_SET_SERVO_CONFIGURATION = 212
    MSP_SET_MOTOR = 214
    MSP_SET_NAV_CONFIG = 215
    MSP_SET_MOTOR_3D_CONFIG = 217
    MSP_SET_RC_DEADBAND = 218
    MSP_SET_RESET_CURR_PID = 219
    MSP_SET_SENSOR_ALIGNMENT = 220
    MSP_SET_LED_STRIP_MODECOLOR = 221
    MSP_SET_MOTOR_CONFIG = 222
    MSP_SET_GPS_CONFIG = 223
    MSP_SET_COMPASS_CONFIG = 224
    MSP_SET_GPS_RESCUE = 225
    MSP_SET_GPS_RESCUE_PIDS = 226
    MSP_SET_VTXTABLE_BAND = 227
    MSP_SET_VTXTABLE_POWERLEVEL = 228
    MSP_MULTIPLE_MSP = 230
    MSP_MODE_RANGES_EXTRA = 238
    MSP_SET_ACC_TRIM = 239
    MSP_ACC_TRIM = 240
    MSP_SERVO_MIX_RULES = 241
    MSP_SET_SERVO_MIX_RULE = 242
    MSP_SET_PASSTHROUGH = 245
    MSP_SET_RTC = 246
    MSP_RTC = 247
    MSP_SET_BOARD_INFO = 248
    MSP_SET_SIGNATURE = 249
    MSP_EEPROM_WRITE = 250
    MSP_RESERVE_1 = 251
    MSP_RESERVE_2 = 252
    MSP_DEBUGMSG = 253
    MSP_DEBUG = 254
    MSP_PASSTHROUGH_ESC_4WAY = 255
    MSP_V2_FRAME = 255
    MSP2_COMMON_SERIAL_CONFIG = 4105
    MSP2_COMMON_SET_SERIAL_CONFIG = 4106
    MSP2_SENSOR_RANGEFINDER_LIDARMT = 7937
    MSP2_SENSOR_OPTICALFLOW_MT = 7938
    MSP2_SENSOR_GPS = 7939
    MSP2_BETAFLIGHT_BIND = 12288
    MSP2_MOTOR_OUTPUT_REORDERING = 12289
    MSP2_SET_MOTOR_OUTPUT_REORDERING = 12290
    MSP2_SEND_DSHOT_COMMAND = 12291
    MSP2_GET_VTX_DEVICE_STATUS = 12292
    MSP2_GET_OSD_WARNINGS = 12293
    MSP2_GET_TEXT = 12294
    MSP2_SET_TEXT = 12295
    MSP2_GET_LED_STRIP_CONFIG_VALUES = 12296
    MSP2_SET_LED_STRIP_CONFIG_VALUES = 12297
    MSP2_SENSOR_CONFIG_ACTIVE = 12298
    MSP2_SENSOR_OPTICALFLOW = 12299
    MSP2_MCU_INFO = 12300
    MSP2_GYRO_SENSOR_ACTIVE = 12301



with open("../msp_messages.json", 'r') as file:
    inavdata = json.load(file)
MSPCodes = build_msp_codes_enum(inavdata)

print(f"{'#':<16}{'INAV':<40} - {'BETAFLIGHT':<40} - Compatible")
for i in range(1,32000):
    try:
        inav = MSPCodes(i).name
        inav_implemented = "not_implemented" not in inavdata[inav]
    except:
        inav = ""
        inav_implemented = False

    try:
        bf = BF_MSPCodes(i).name
    except:
        bf = ""
    
    if inav == bf and inav_implemented:
        agree = "Match"
    elif inav_implemented and bf and (inav in bf or bf in inav):
        agree = "Close match"
    elif inav==bf and not inav_implemented:
        agree = "Not Implemented"
    else:
        agree = ""


    if inav or bf: 
        print(f"{i:<16}{inav:<40} - {bf:<40} - {agree}")

 
