#!/usr/bin/env python3
"""
Generate a C header from an MSP message schema.

Usage:
  python test_gen_c.py path/to/msp_messages.json [-o msp.h]
"""
import argparse
import json
import re
import sys
from pathlib import Path

# Maps JSON ctype to C type
CTYPE_MAP = {
    "uint8_t": "uint8_t",
    "int8_t": "int8_t",
    "uint16_t": "uint16_t",
    "int16_t": "int16_t",
    "uint32_t": "uint32_t",
    "int32_t": "int32_t",
    "uint64_t": "uint64_t",
    "int64_t": "int64_t",
    "float": "float",
    "char": "char",
    "char[]": "char[]",           # special handled
}

IDENT_RE = re.compile(r"[^a-zA-Z0-9_]")

def norm_ident(s: str) -> str:
    return IDENT_RE.sub("_", s)

def ctype_from_entry(entry: dict) -> str:
    # If an explicit enum type is provided, use it as-is
    ctype = entry.get("ctype", "")
    if ctype in CTYPE_MAP:
        return CTYPE_MAP[ctype]
    # array forms like "char[4]" or "uint16_t[OSD_ITEM_COUNT]"
    m = re.match(r"^([a-zA-Z0-9_]+)\s*\[(.+)\]$", ctype)
    if m:
        base = m.group(1)
        arrn = m.group(2)
        base_c = CTYPE_MAP.get(base, base)
        return f"{base_c}[{arrn}]"
    # fallback to literal
    return ctype
# returns (base, size) where size is:
#   None  -> scalar (no brackets)
#   ""    -> unsized []  (variable length)
#   "EXPR"-> sized [EXPR]
CTYPE_SPLIT_RE = re.compile(r"\s*([A-Za-z_]\w*)\s*(?:\[\s*(.*?)\s*\])?\s*$")

def split_ctype(ctype_raw: str):
    m = CTYPE_SPLIT_RE.fullmatch(ctype_raw or "")
    if not m:
        # unknown literal, fall back to as-is scalar
        return (ctype_raw, None)
    base = CTYPE_MAP.get(m.group(1), m.group(1))
    size = m.group(2)
    if size is None:
        return (base, None)
    # treat "": unsized (i.e., type[])
    return (base, size)
def field_decl(entry: dict, suffix_comment: str = "") -> str:
    name = norm_ident(entry["name"])
    desc = (entry.get("desc") or "").strip()
    units = (entry.get("units") or "").strip()
    enum_t = entry.get("enum")

    array_flag        = bool(entry.get("array"))
    array_size        = entry.get("array_size", 0)
    array_size_define = (entry.get("array_size_define") or "").strip()
    ctype_raw         = (entry.get("ctype") or "").strip()

    def pick_base(default: str) -> str:
        if enum_t and default in ("uint8_t", "int8_t", "uint16_t", "int16_t", "uint32_t", "int32_t", "uint64_t", "int64_t", ""):
            return enum_t
        return default

    if ctype_raw == "Varies":
        basetype = "uint8_t"
        declarator = f"{name}[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
        cmts = []
        if desc: cmts.append(desc)
        if units: cmts.append(f"units: {units}")
        if suffix_comment: cmts.append(suffix_comment)
        cmt = "  // " + " | ".join(cmts) if cmts else ""
        return f"    {basetype} {declarator};{cmt}"

    # Decide base + declarator
    if array_flag:
        base = pick_base(CTYPE_MAP.get(ctype_raw, ctype_raw))
        if array_size_define!="":
            declarator = f"{name}[{array_size_define}]"
        elif isinstance(array_size, int) and array_size > 0:
            declarator = f"{name}[{array_size}]"
        else:
            # variable length (unknown at compile-time)
            declarator = f"{name}[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
        basetype = base
    else:
        base_raw, size = split_ctype(ctype_raw)
        base = pick_base(base_raw)
        if size is None:
            basetype, declarator = base, name
        elif size == "":
            basetype, declarator = base, f"{name}[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
        else:
            basetype, declarator = base, f"{name}[{size}]"

    cmts = []
    if desc: cmts.append(desc)
    if units: cmts.append(f"units: {units}")
    if enum_t: cmts.append(f"Enum: {enum_t}")
    if array_flag and array_size_define:
        cmts.append(f"length via {array_size_define}")
    if suffix_comment: cmts.append(suffix_comment)
    cmt = "  // " + " | ".join(cmts) if cmts else ""
    return f"    {basetype} {declarator};{cmt}"


def emit_header_preamble():
    return """#pragma once
// Auto-generated by gen_msp_header.py. Do not edit by hand.

#include <stdint.h>
#include "msp_protocol.h"
#include "all_defines.h"
#include "all_enums.h"

#ifndef BUILD_DATE_LENGTH
#define BUILD_DATE_LENGTH 11
#endif
#ifndef BUILD_TIME_LENGTH
#define BUILD_TIME_LENGTH 8
#endif
#ifndef GIT_SHORT_REVISION_LENGTH
#define GIT_SHORT_REVISION_LENGTH 8
#endif
#ifndef OSD_CHAR_VISIBLE_BYTES
#define OSD_CHAR_VISIBLE_BYTES 54
#endif
#ifndef OSD_CHAR_BYTES
#define OSD_CHAR_BYTES 64
#endif
#ifndef DEBUG32_VALUE_COUNT
#define DEBUG32_VALUE_COUNT 8
#endif
#ifndef CHECKBOX_ITEM_COUNT
#define CHECKBOX_ITEM_COUNT 60
#endif

#ifndef MSP_HAS_BOXBITMASK_T
#define MSP_HAS_BOXBITMASK_T
typedef struct {
    uint32_t bits[(CHECKBOX_ITEM_COUNT + 31) / 32];
} boxBitmask_t;
#endif

#ifndef MSP_HAS_ESC_SENSOR_T
#define MSP_HAS_ESC_SENSOR_T
typedef struct {
    uint8_t dataAge;
    int16_t temperature;
    int16_t voltage;
    int32_t current;
    uint32_t rpm;
} escSensorData_t;
#endif

#ifndef MSP_HAS_LED_CONFIG_T
#define MSP_HAS_LED_CONFIG_T
typedef struct {
    uint16_t led_position;
    uint16_t led_function;
    uint16_t led_overlay;
    uint16_t led_color;
    uint16_t led_direction;
    uint16_t led_params;
} ledConfig_t;
#endif

#ifndef MSP_HAS_VARIES_T
#define MSP_HAS_VARIES_T
typedef uint8_t Varies;
#endif

#ifndef MSP_HAS_NAV_USER_CONTROL_MODE_E
#define MSP_HAS_NAV_USER_CONTROL_MODE_E
typedef uint8_t navUserControlMode_e;
#endif
#ifndef MSP_HAS_NAV_RTH_ALT_CONTROL_MODE_E
#define MSP_HAS_NAV_RTH_ALT_CONTROL_MODE_E
typedef uint8_t navRthAltControlMode_e;
#endif
#ifndef MSP_HAS_MIXER_PRESET_E
#define MSP_HAS_MIXER_PRESET_E
typedef uint16_t mixerPreset_e;
#endif
#ifndef MSP_HAS_FENCE_ACTION_E
#define MSP_HAS_FENCE_ACTION_E
typedef uint8_t fenceAction_e;
#endif

#if !defined(MSP_PROTOCOL_VERSION)
# error "msp_protocol.h must be present and define protocol macros"
#endif

#if defined(_MSC_VER)
#  pragma pack(push, 1)
#  define MSP_PACKED
#else
#  define MSP_PACKED __attribute__((__packed__))
#endif

// Placeholder size for variable length arrays when the exact length is unknown at compile time
#ifndef UNDEFINED_LEN_ARRAY_PLACEHOLDER
#define UNDEFINED_LEN_ARRAY_PLACEHOLDER 1
#endif

"""

def emit_header_postamble():
    return """
#if defined(_MSC_VER)
#  pragma pack(pop)
#endif
"""

def emit_struct(name: str, payload: list, parent_msg: dict) -> str:
    lines = []
    lines.append(f"typedef struct __attribute__((packed)) {{")

    for ent in payload:
        # Repeating block → emit an anonymous packed struct array member
        if isinstance(ent, dict) and ent.get("repeating") and "payload" in ent:
            arr_name = norm_ident(ent.get("name", "items"))
            rep = ent.get("repeating")
            # decide bracket expression
            if isinstance(rep, int) and rep > 0:
                bracket = f"[{rep}]"
            elif isinstance(rep, str) and rep.strip():
                rep_clean = rep.strip()
                if any(ch.islower() for ch in rep_clean):
                    bracket = "[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"
                else:
                    bracket = f"[{rep_clean}]"
            else:
                bracket = "[UNDEFINED_LEN_ARRAY_PLACEHOLDER]"

            inner_payload = ent["payload"]
            if (isinstance(inner_payload, list) and len(inner_payload) == 1
                    and isinstance(inner_payload[0], dict) and "payload" in inner_payload[0]):
                inner_payload = inner_payload[0]["payload"]

            # one declaration: struct MSP_PACKED { ... } items[...];
            lines.append(f"    struct MSP_PACKED {{")
            for sub in inner_payload:
                lines.append(field_decl(sub))
            lines.append(f"    }} {arr_name}{bracket};  // repeating: {rep}")
            continue

        # Normal field
        lines.append(field_decl(ent))

    lines.append(f"}} {name};\n")
    return "\n".join(lines)



def pick_variant_suffix(key: str) -> str:
    # Make a short safe suffix from the variant key
    # For examples like "dataSize >= 10" -> "_dataSize_ge_10"
    s = key.strip()
    s = s.replace(">=", "ge").replace("==", "eq").replace("<=", "le").replace(">", "gt").replace("<", "lt").replace(" ", "_")
    s = IDENT_RE.sub("_", s)
    return "_" + s

def main():
    parser = argparse.ArgumentParser(description="Generate MSP C header from schema JSON.")
    parser.add_argument("schema", help="Path to msp_messages.json")
    parser.add_argument("-o", "--out", default="msp.h", help="Output header path (default: msp.h)")
    args = parser.parse_args()

    data = json.loads(Path(args.schema).read_text())
    out = []
    out.append(emit_header_preamble())

    # Forward declare a tag enum for message ids that maps to your existing defines - NO, AWFUL, BAD CLANKER, VERY BAD

    # Emit one struct per message or per variant
    for msg_name, msg in data.items():
        desc = (msg.get("description") or "").strip()
        notes = (msg.get("notes") or "").strip()
        code = int(msg.get("code"))
        mspv = int(msg.get("mspv") or (1 if code <= 255 else 2))
        reply = msg.get("reply") or {}
        request = msg.get("request") or {}
        variants = msg.get("variants")

        safe_msg_name = norm_ident(msg_name)
        base_struct = f"{safe_msg_name}_reply_t"
        base_req_struct = f"{safe_msg_name}_request_t"

        out.append(f"// {msg_name} (MSPv{mspv})")
        if desc:
            out.append(f"// {desc}")
        if notes:
            out.append(f"// Notes: {notes}")
        out.append("")

        # Variants: each variant gets its own struct with a suffix
        if variants:
            for vkey, v in variants.items():
                suffix = pick_variant_suffix(vkey)
                # request variant
                if "request" in v and v["request"] and "payload" in v["request"]:
                    out.append(emit_struct(base_req_struct + suffix, v["request"]["payload"], msg))
                # reply variant
                if "payload" in v:
                    out.append(emit_struct(base_struct + suffix, v["payload"], msg))
            continue

        # Non-variant request
        if request and "payload" in request and request["payload"]:
            out.append(emit_struct(base_req_struct, request["payload"], msg))
        # Non-variant reply
        if reply and "payload" in reply and reply["payload"]:
            out.append(emit_struct(base_struct, reply["payload"], msg))

    out.append(emit_header_postamble())
    Path(args.out).write_text("\n".join(out))

if __name__ == "__main__":
    main()
