#!/usr/bin/env python3
import json
import re
import sys
from pathlib import Path

# Maps JSON ctype to C type
CTYPE_MAP = {
    "uint8_t": "uint8_t",
    "int8_t": "int8_t",
    "uint16_t": "uint16_t",
    "int16_t": "int16_t",
    "uint32_t": "uint32_t",
    "int32_t": "int32_t",
    "uint64_t": "uint64_t",
    "int64_t": "int64_t",
    "char": "char",
    "char[]": "char[]",           # special handled
}

IDENT_RE = re.compile(r"[^a-zA-Z0-9_]")

def norm_ident(s: str) -> str:
    return IDENT_RE.sub("_", s)

def ctype_from_entry(entry: dict) -> str:
    # If an explicit enum type is provided, use it as-is
    if "enum" in entry and entry["enum"]:
        return entry["enum"]
    ctype = entry.get("ctype", "")
    if ctype in CTYPE_MAP:
        return CTYPE_MAP[ctype]
    # array forms like "char[4]" or "uint16_t[OSD_ITEM_COUNT]"
    m = re.match(r"^([a-zA-Z0-9_]+)\s*\[(.+)\]$", ctype)
    if m:
        base = m.group(1)
        arrn = m.group(2)
        base_c = CTYPE_MAP.get(base, base)
        return f"{base_c}[{arrn}]"
    # fallback to literal
    return ctype

def field_decl(entry: dict, suffix_comment: str = "") -> str:
    name = norm_ident(entry["name"])
    desc = entry.get("desc", "").strip()
    units = entry.get("units", "").strip()
    ctype_raw = entry.get("ctype", "")
    enum_t = entry.get("enum")
    array = entry.get("array", False)
    array_ctype = entry.get("array_ctype")
    array_size = entry.get("array_size", 0)

    # Compute C type and declarator
    if enum_t:
        # Always use the tag form; safe in C even if a typedef also exists
        basetype = enum_t if enum_t.startswith("enum ") else f"enum {enum_t}"
        declarator = name
    elif array:
        # Explicit array details override generic ctype
        if isinstance(array_size, int) and array_size > 0:
            basetype = CTYPE_MAP.get(array_ctype, array_ctype)
            declarator = f"{name}[{array_size}]"
        elif isinstance(array_size, str) and array_size:
            basetype = CTYPE_MAP.get(array_ctype, array_ctype)
            declarator = f"{name}[{array_size}]"
        else:
            # flexible array
            basetype = CTYPE_MAP.get(array_ctype, array_ctype)
            declarator = f"{name}[]"
    else:
        # ctype could be like "char[4]" which we need to split
        m = re.match(r"^([a-zA-Z0-9_]+)\s*\[(.+)\]$", ctype_raw)
        if m:
            base = CTYPE_MAP.get(m.group(1), m.group(1))
            sz = m.group(2)
            basetype = base
            declarator = f"{name}[{sz}]"
        elif ctype_raw == "char[]":
            basetype = "char"
            declarator = f"{name}[]"
        else:
            basetype = CTYPE_MAP.get(ctype_raw, ctype_raw)
            declarator = name

    cmts = []
    if desc:
        cmts.append(desc)
    if units:
        cmts.append(f"units: {units}")
    if suffix_comment:
        cmts.append(suffix_comment)
    cmt = "  // " + " | ".join(cmts) if cmts else ""
    return f"    {basetype} {declarator};{cmt}"

def emit_header_preamble():
    return """#pragma once
// Auto-generated by gen_msp_header.py. Do not edit by hand.

#include <stdint.h>
#include "msp_protocol.h"
#include "all_enums.h"
#include "all_defines.h"

#if !defined(MSP_PROTOCOL_VERSION)
# error "msp_protocol.h must be present and define protocol macros"
#endif

#if defined(_MSC_VER)
#  pragma pack(push, 1)
#  define MSP_PACKED
#else
#  define MSP_PACKED __attribute__((__packed__))
#endif

"""

def emit_header_postamble():
    return """
#if defined(_MSC_VER)
#  pragma pack(pop)
#endif
"""

def emit_struct(name: str, payload: list, parent_msg: dict) -> str:
    lines = []
    lines.append(f"typedef struct MSP_PACKED {name} {{")
    # Some messages declare a count field elsewhere that controls flexible arrays.
    # We simply trust the order given in JSON. If there is a flexible array, it must be last to be valid C.
    for ent in payload:
        # nested repeating block
        if "payload" in ent and ent.get("repeating"):
            # create an inner struct type name
            inner_name = f"{name}__{norm_ident(ent.get('name','repeating')) or 'block'}_t"
            inner_payload = ent["payload"]
            # Flatten single-element wrappers
            if isinstance(inner_payload, list) and len(inner_payload) == 1 and "payload" in inner_payload[0]:
                inner_payload = inner_payload[0]["payload"]
            # Emit inner struct
            lines.append(f"    // Repeating block: {ent.get('repeating')}")
            lines.append(f"    struct MSP_PACKED {inner_name} {{")
            for sub in inner_payload:
                lines.append(field_decl(sub))
            lines.append(f"    }};")
            # Now the flexible array of that inner struct
            rep_count = str(ent.get("repeating"))
            # If repeating is a macro or field name, leave brackets flexible. C requires last member be flexible.
            lines.append(f"    struct {inner_name} {norm_ident(ent.get('name','items'))}[];  // count by field or macro: {rep_count}")
        else:
            lines.append(field_decl(ent))
    lines.append(f"}} {name};\n")
    return "\n".join(lines)

def pick_variant_suffix(key: str) -> str:
    # Make a short safe suffix from the variant key
    # For examples like "dataSize >= 10" -> "_dataSize_ge_10"
    s = key.strip()
    s = s.replace(">=", "ge").replace("==", "eq").replace("<=", "le").replace(">", "gt").replace("<", "lt").replace(" ", "_")
    s = IDENT_RE.sub("_", s)
    return "_" + s

def main():
    if len(sys.argv) != 2:
        print("usage: gen_msp_header.py <spec.json>", file=sys.stderr)
        sys.exit(1)

    data = json.loads(Path(sys.argv[1]).read_text())
    out = []
    out.append(emit_header_preamble())

    # Forward declare a tag enum for message ids that maps to your existing defines - NO, AWFUL, BAD CLANKER, VERY BAD

    # Emit one struct per message or per variant
    for msg_name, msg in data.items():
        desc = msg.get("description", "").strip()
        notes = msg.get("notes", "").strip()
        mspv = msg.get("mspv", "")
        reply = msg.get("reply")
        request = msg.get("request")
        variants = msg.get("variants")

        safe_msg_name = norm_ident(msg_name)
        base_struct = f"{safe_msg_name}_reply_t"
        base_req_struct = f"{safe_msg_name}_request_t"

        out.append(f"// {msg_name} (MSPv{mspv})")
        if desc:
            out.append(f"// {desc}")
        if notes:
            out.append(f"// Notes: {notes}")
        out.append("")

        # Variants: each variant gets its own struct with a suffix
        if variants:
            for vkey, v in variants.items():
                suffix = pick_variant_suffix(vkey)
                # request variant
                if "request" in v and v["request"] and "payload" in v["request"]:
                    out.append(emit_struct(base_req_struct + suffix, v["request"]["payload"], msg))
                # reply variant
                if "payload" in v:
                    out.append(emit_struct(base_struct + suffix, v["payload"], msg))
            continue

        # Non-variant request
        if request and "payload" in request and request["payload"]:
            out.append(emit_struct(base_req_struct, request["payload"], msg))
        # Non-variant reply
        if reply and "payload" in reply and reply["payload"]:
            out.append(emit_struct(base_struct, reply["payload"], msg))

    out.append(emit_header_postamble())
    with open("msp.h","w+") as file:
        file.write("\n".join(out))

if __name__ == "__main__":
    main()
